"""Add accepted_at field to RoomMember model

Revision ID: a8c4d37510b7
Revises: achievement_models_001
Create Date: 2025-07-27 04:21:52.959204

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8c4d37510b7'
down_revision: Union[str, Sequence[str], None] = 'achievement_models_001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('room_member', sa.Column('accepted_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('room_member', 'accepted_at')
    # ### end Alembic commands ###
